GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{
    "title": "New Test Post with Author",
    "author": ["649a136dce72379d44077570"],
    "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/NewTestPost.html"
}

###
DELETE http://localhost:3003/api/blogs/5a422a851b54a676234d17f7

###
POST http://localhost:3003/api/users HTTP/1.1
Content-Type: application/json

{
    "username": "testuser",
    "name": "Root test",
    "password": "testytest"
}

###
POST http://localhost:3003/api/login HTTP/1.1
Content-Type: application/json

{
    "username": "testuser",
    "password": "testytest"
}